spring:
  application:
    name: sharesAnalysiser
  jackson:
    time-zone: GMT+8
server:
  port: 8080
  servlet:
    context-path: /yyshare
logging:
  config:  classpath:logback-spring.xml
dao:
  executors:
    excel: com.yyshare.dao.excel.ExcelExecutor
  def: excel